apiVersion: v1
kind: Pod
metadata:
  name: gastrovision-training-1
spec:
  nodeSelector:
    nautilus.io/linstor: "true"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:  
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-A10
            - NVIDIA-GeForce-RTX-3090
            - NVIDIA-GeForce-RTX-4090
            - NVIDIA-RTX-A6000
            - Quadro-RTX-8000
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
  containers:
    - name: gastrovision-swin-training
      image: nvcr.io/nvidia/pytorch:24.09-py3
      env:
        - name: WANDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: wandb-credentials
              key: api-key
        - name: WANDB_PROJECT
          value: "gastrovision-challenge"
        - name: WANDB_ENTITY
          value: "timgsereda"
      command: ["/bin/bash", "-c"]
      args:
        - |
          echo "--- 1. Installing dependencies ---"
          apt-get update && apt-get install -y git wget unzip
          pip install torch>=2.0.0 torchvision>=0.15.0 --index-url https://download.pytorch.org/whl/cu118
          pip install timm>=0.9.0 albumentations>=1.3.0 wandb>=0.15.0 \
                      Pillow>=9.0.0 numpy>=1.24.0 scikit-learn>=1.3.0 \
                      pandas>=2.0.0 tqdm>=4.65.0
          
          echo "--- 2. Cloning training repository ---"
          cd /workspace
          git clone https://github.com/tsereda/GastroVision-Challenge.git
          cd GastroVision-Challenge/gastrovision

          echo "--- 3. Preparing GastroVision dataset ---"
          # TODO: Add your dataset download/unzip commands here
          # Example:
          # gdown <your-dataset-id>
          # unzip gastrovision-dataset.zip -d /data/gastrovision
          
          echo "--- 4. Verifying environment ---"
          python -c "import torch; import timm; import albumentations; import wandb; \
                     print(f'PyTorch: {torch.__version__}'); \
                     print(f'TIMM: {timm.__version__}'); \
                     print(f'CUDA available: {torch.cuda.is_available()}'); \
                     print(f'GPU: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else \"None\"}')"
          
          echo "--- 5. Running W&B hyperparameter sweep ---"
          # Initialize sweep (run this once to get sweep ID)
          # wandb sweep config/sweep.yaml
          
          # Run sweep agent (replace with your sweep ID)
          # wandb agent timgsereda/gastrovision-challenge/<sweep-id> --count 50
          
          # Or run single training
          # python train.py
          
          echo "--- IMPORTANT: Update this pod with your sweep ID ---"
          echo "--- Keeping pod alive for debugging ---"
          tail -f /dev/null
      
      volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: data
          mountPath: /data
        - name: shm
          mountPath: /dev/shm
      resources:
        requests:
          memory: 32Gi
          cpu: "8"
          nvidia.com/gpu: "1"
        limits:
          memory: 64Gi
          cpu: "16"
          nvidia.com/gpu: "1"
  
  volumes:
    - name: workspace
      emptyDir:
        sizeLimit: 100Gi
    - name: data
      persistentVolumeClaim:
        claimName: gastrovision-data-1
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 16Gi
  
  restartPolicy: Never
